(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/progress/CustomProgress"],{1849:function(t,e,r){"use strict";r.r(e);var n=r("787c"),a=r.n(n);for(var o in n)["default"].indexOf(o)<0&&function(t){r.d(e,t,(function(){return n[t]}))}(o);e["default"]=a.a},"6b5f":function(t,e,r){"use strict";var n=r("f6bc"),a=r.n(n);a.a},"787c":function(t,e,r){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;e.default={props:{value:{type:Number,default:25,required:!0},progress_time:{type:Number,default:1500},progress_width:{type:Number,default:250},progress_height:{type:Number,default:125},border_width:{type:Number,default:12},bg_color:{type:String,default:"#E2E2E2"},start_color:{type:String,default:"#FFE97C"},end_color:{type:String,default:"#FFE97C"}},data:function(){return{percent:0}},mounted:function(){this.drawProgressbg(),this.drawCircle(this.value)},methods:{drawProgressbg:function(){var e=t.createCanvasContext("cpbg",this);e.setLineWidth(this.border_width),e.setStrokeStyle(this.bg_color),e.setLineCap("round"),e.beginPath(),e.arc(125,125,100,.99*Math.PI,.01*Math.PI,!1),e.stroke(),e.draw()},drawCircle:function(e){var r=this;if(0!==e){var n=Math.floor(this.progress_time/100),a=t.createCanvasContext("cpbar",this),o=a.createLinearGradient(28,55,192,55);o.addColorStop("0",this.start_color),o.addColorStop("1.0",this.end_color),a.setLineWidth(this.border_width),a.setStrokeStyle(o),a.setLineCap("round"),a.beginPath(),e=.01*e+.99,1===e&&(e=.99),e>=2&&(e%=2),1.99===e&&(e=.01),a.arc(125,125,100,.99*Math.PI,e*Math.PI,!1),a.stroke(),a.draw(),this.value>this.percent&&(this.percent++,setTimeout((function(){r.drawCircle(r.percent)}),n))}}}}}).call(this,r("255a")["default"])},"90d8":function(t,e,r){"use strict";var n;r.d(e,"b",(function(){return a})),r.d(e,"c",(function(){return o})),r.d(e,"a",(function(){return n}));var a=function(){var t=this,e=t.$createElement;t._self._c},o=[]},"9fb0":function(t,e,r){"use strict";r.r(e);var n=r("90d8"),a=r("1849");for(var o in a)["default"].indexOf(o)<0&&function(t){r.d(e,t,(function(){return a[t]}))}(o);r("6b5f");var i,u=r("7702"),s=Object(u["a"])(a["default"],n["b"],n["c"],!1,null,null,null,!1,n["a"],i);e["default"]=s.exports},f6bc:function(t,e,r){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/progress/CustomProgress-create-component',
    {
        'components/progress/CustomProgress-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('255a')['createComponent'](__webpack_require__("9fb0"))
        })
    },
    [['components/progress/CustomProgress-create-component']]
]);
